## 🔄 NumPy `sort()` vs Python `sorted()`

#### 1️⃣ NumPy `sort()`
- Return a sorted copy of an array.
- 🧩 **Library function** → Part of NumPy, designed for arrays.  
- ⚡ **Optimized for speed** → Uses C backend, very fast for large numerical data.  
- 📤 **Returns a new sorted array** (original unchanged).  
- 🔄 Can sort along a specific **axis** in multi‑dimensional arrays.  
-  https://numpy.org/doc/stable/reference/generated/numpy.sort.html

#### 2️⃣ Python `sorted()`
- 🧩 **Built‑in function** → Works on any iterable (lists, tuples, sets, strings).  
- 🐍 **General purpose** → Not optimized for numerical computing.  
- 📤 **Returns a new sorted list** (original unchanged).  
- 🎯 Flexible → Can use `key` and `reverse` parameters for custom sorting.  

<br>


| Feature                | NumPy `sort()` 🧩 | Python `sorted()` 🐍 |
|-------------------------|------------------|----------------------|
| **Belongs to**          | NumPy library    | Built‑in function    |
| **Works on**            | NumPy arrays     | Any iterable (list, tuple, set, string) |
| **Return type**         | New NumPy array  | New Python list      |
| **Speed**               | Very fast (C backend, optimized for large arrays) ⚡ | Slower for large data, general purpose |
| **Axis support**        | Yes (can sort along rows/columns in multi‑dim arrays) 🔄 | No axis concept, sorts entire iterable |
| **Custom key support**  | Limited (no `key` parameter) | Flexible (`key` and `reverse` supported) 🎯 |
| **Original data**       | Unchanged (non‑destructive) | Unchanged (non‑destructive) |
| **Best use case**       | Numerical computing, large datasets 📊 | General collections, custom sorting logic 📝 |

<br>
<br>


### 💹 1. Numpy `Sort`:

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([75, 92, 14, 37, 11, 76, 92,  9, 51, 83, 29, 82, 66, 78,  3],
      dtype=int32)

#### A. ✨ `np.sort(a)` → `Ascending` order.

In [9]:
np.sort(a)

array([12, 12, 19, 37, 41, 52, 56, 57, 58, 58, 62, 62, 79, 90, 91],
      dtype=int32)

#### ✨ B. `np.sort(a)[::-1]` → `Descending` order.

In [10]:
np.sort(a)[::-1]

array([91, 90, 79, 62, 62, 58, 58, 57, 56, 52, 41, 37, 19, 12, 12],
      dtype=int32)

### 💹 2. Python `Sorted`:

In [11]:
nums = [3, 1, 2]
print(sorted(nums))       # [1, 2, 3]
print(nums)   

[1, 2, 3]
[3, 1, 2]


### 💹 3. Numpy `Sort 2-D`:

In [20]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[56, 76, 18, 51],
       [41, 67, 65, 11],
       [50, 76, 76, 33],
       [ 3,  2, 64,  3],
       [95, 35,  8, 80],
       [92, 22, 71, 80]], dtype=int32)

 #### A. `axis=0` = 📊 vertical sort (**column-wise** (down each `column`)).  


In [13]:
np.sort(b,axis=0)

array([[ 7, 32, 24, 14],
       [ 9, 37, 27, 16],
       [24, 39, 28, 22],
       [68, 51, 44, 27],
       [88, 81, 51, 77],
       [89, 97, 93, 96]], dtype=int32)

#### B. `axis=1` = 📈 horizontal sort (**row-wise** (across each `row`)).  

In [14]:
np.sort(b,axis=1)

array([[27, 27, 32, 89],
       [37, 51, 77, 88],
       [16, 44, 68, 97],
       [ 9, 14, 81, 93],
       [24, 24, 51, 96],
       [ 7, 22, 28, 39]], dtype=int32)

---

<br>

## 2️⃣ np.`append`

- The `numpy.append()` appends values along the mentioned axis at the end of the array
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

### #️⃣ A. `Append 1-D` array

In [19]:
a

array([93, 47,  8,  5, 51, 56, 12,  9, 88, 59, 42, 19, 87, 66, 58],
      dtype=int32)

In [20]:
# code
np.append(a,200)

array([ 93,  47,   8,   5,  51,  56,  12,   9,  88,  59,  42,  19,  87,
        66,  58, 200])

### #️⃣ B. `Append 2-D` array
- `np.append(arr, values, axis)` → adds values to an array.
- If `axis=None` → flattens both arrays before appending (not usually what you want for 2‑D).
- If `axis=0` → append rows (`vertical stacking`).
- If `axis=1` → append columns (`horizontal stacking`). #️⃣ Only focus on `Horizontal Appending` <span style="color: red; font-weight: bold;">Not vertical</span>

In [44]:
b

array([[96,  7,  2,  8],
       [38, 26, 93, 94],
       [75, 42, 68,  2],
       [95, 20, 72, 20],
       [44, 10, 26, 90],
       [49, 58, 79, 45]], dtype=int32)

In [47]:
np.random.random((b.shape[0],1))

array([[0.23508822],
       [0.37320678],
       [0.68398809],
       [0.00227538],
       [0.34403309],
       [0.98908628]])

In [49]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[96.        ,  7.        ,  2.        ,  8.        ,  0.65782373],
       [38.        , 26.        , 93.        , 94.        ,  0.29834248],
       [75.        , 42.        , 68.        ,  2.        ,  0.8834288 ],
       [95.        , 20.        , 72.        , 20.        ,  0.82833271],
       [44.        , 10.        , 26.        , 90.        ,  0.76430935],
       [49.        , 58.        , 79.        , 45.        ,  0.26447508]])

---

## 3️⃣ `np.concatenate`

- **numpy.concatenate()** function concatenate `a sequence of arrays` along an existing axis.
- `concatenate` = join arrays along axis.
- `Shapes must match` in all other dimensions.
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


#### A. ✨ **axis=0** → `vertical stacking` (rows).

In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### B. ✨ **axis=1** → `horizontal stacking` (columns).

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

---

## 🚀 4️⃣ `np.unique`

- With the help of np.unique() method, we can get the `unique values from an array` given as parameter in np.unique() method.
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

---

## 🚀 5️⃣ `np.expand_dims`

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[11],
       [53],
       [28],
       [50],
       [38],
       [37],
       [94],
       [92],
       [ 5],
       [30],
       [68],
       [ 9],
       [78],
       [ 2],
       [21]])

---

## 🚀 6️⃣ `np.where`

### 1️⃣ Basic Usage
- `np.where(condition)` → returns the **indices** where the condition is `True`.  
- Output is a tuple of arrays (one per dimension). 
- https://numpy.org/doc/stable/reference/generated/numpy.where.html
  
### 2️⃣ Conditional Selection
- `np.where(condition, x, y)` → element‑wise choice.  
- If condition is `True` → pick from `x`.  
- If condition is `False` → pick from `y`.  

### 3️⃣ Exam‑style Takeaway
- ✨ `np.where(condition)` → gives indices.  
- ✨ `np.where(condition, x, y)` → acts like vectorized **if‑else**.  
- ✅ Shortcut:  
  - **One argument** → indices.  
  - **Three arguments** → conditional selection.  

#### 🍄 Example 1: `1-D` find all `indices with value greater than 50`

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [51]:
np.where(a>50)

(array([ 0,  4,  5,  8,  9, 12, 13, 14]),)

#### 🍄 Example 2: `1-D` `replace all values > 50 with 0`

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

#### 🍄 Example 3: `1-D` `replace all values divisible by 2 with 0`

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

---

## 7️⃣ 🚀 `np.argmax`

#### 🅰️ Purpose
- Returns the **index of the maximum value** in an array.  
- If the array is multi‑dimensional, you can specify an **axis**.  
- `axis=0`=**column‑wise max indices**; `axis=1` → **row‑wise max indices** 
- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html



#### 🅱️ Basic Example
```python
import numpy as np
a = np.array([10, 50, 30, 20])
print(np.argmax(a))   # 1
```
👉 Index `1` because `50` is the largest element.


#### `𝓒.` With Axis
```python
b = np.array([[1, 7, 3],
              [9, 2, 5]])

print(np.argmax(b, axis=0))  # [1 0 1]
print(np.argmax(b, axis=1))  # [1 0]
```

- `axis=0` → column‑wise max indices  
  - Col1 → max at row1 (`9`) → index 1  
  - Col2 → max at row0 (`7`) → index 0  
  - Col3 → max at row1 (`5`) → index 1  

- `axis=1` → row‑wise max indices  
  - Row1 → max at col2 (`7`) → index 1  
  - Row2 → max at col0 (`9`) → index 0  


#### 📝 Exam‑style Takeaway
- ✨ `np.argmax(a)` → index of max in flattened array.  
- ✨ `np.argmax(a, axis=0)` → indices of max values down each column.  
- ✨ `np.argmax(a, axis=1)` → indices of max values across each row.  

<br>
<br>


#### 🍄 Example 1: `1-D` find all `indices of Maximum value`

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.argmax(a)

6

#### 🍄 Example 2: `2-D` find all `indices of Maximum value`
- ✨ `np.argmax(a, axis=0)` → indices of max values down each `column.`  
- ✨ `np.argmax(a, axis=1)` → indices of max values across each `row.`  

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

---

## 🚀 8️⃣ `np.argmin`
- ✨ `np.argmax(a, axis=0)` → `indices` of `min` values down each `column.`  
- ✨ `np.argmax(a, axis=1)` → `indices` of `min` values across each `row.`  

In [ ]:
# np.argmin
np.argmin(a)

13

---

## 🚀 9️⃣ `np.cumsum`

- `numpy.cumsum()` function is used when we want to compute the `cumulative sum of array elements` over a given axis.
- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

**syntex:** `np.cumsum(a, axis=None, dtype=None, out=None)`


**Parameters:**
- `a` → Input array.
- `axis` → Axis along which `cumulative sum` is computed.
  - `None` (default): Flattens array before summing.
  - `0`: **Column-wise** cumulative sum.
  - `1`: **Row-wise** cumulative sum.
- `dtype` → Data type of the result (optional).
- `out` → Output array to store results (optional).

#### 🍄 **Example 1:** `1-D cumulative sum`

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

#### 🍄 **Example 2:** `2-D cumulative sum`
  - `0`: **Column-wise** cumulative sum.
  - `1`: **Row-wise** cumulative sum.

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 12,  64, 106, 112],
       [ 29,  47,  94, 149],
       [ 61, 154, 237, 246],
       [ 38, 101, 145, 230],
       [  8,  95, 126, 198],
       [ 40, 111, 113, 120]])

In [ ]:
np.cumsum(b)

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

---

## 🚀🔟 `np.cumprod`
- Computes the **cumulative product** of elements.
- Each element in the result is the product of all previous elements up to that position.

**syntex:** `np.cumsum(a, axis=None, dtype=None, out=None)`

**Parameters:**
- `a` → Input array.
- `axis` → Axis along which `cumulative sum` is computed.
  - `None` (default): Flattens array before summing.
  - `0`: **Column-wise** cumulative sum.
  - `1`: **Row-wise** cumulative sum.
- `dtype` → Data type of the result (optional).
- `out` → Output array to store results (optional).

#### 🍄 **Example :** `1-D cumulative product`

In [16]:
# np.cumprod
np.cumprod(a)

array([                  12,                  144,                13104,
                     484848,             27151488,           1547634816,
                29405061504,        2646455535360,      108504676949760,
           6293271263086080,   365009733258992640,  4183859388347992064,
       -3800240690419032064,  4192750152244183040,  -814131299481468928])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

---

## **11.**  🚀 `np.percentile`

- `numpy.percentile()` function used to compute the nth percentile of the given data (array elements) along the specified axis. 
- Computes the value at a given percentile of the data.
  - Example: The `50th percentile` = median.
- Useful for descriptive statistics, quartiles, and data distribution analysis.
- https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

**syntex:** `np.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear')`

- `a` → Input array.
- `q` → `Percentile(s)` to compute (0–100).
  - Can be a single value (e.g., 50) or a list/array (e.g., [25, 50, 75]).
- `axis → Axis along which percentiles are computed.
  - `None` (default): Flattens the array.
  - `0`: `Column-wise` percentiles.
  - `1`: `Row-wise` percentiles.
- `out` → Optional array to store results.
- `overwrite_input` → If True, may overwrite input for efficiency.
- `method` → Interpolation method (`linear`, `nearest`, `lower`, `higher`, `midpoint`).

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.percentile(a,50)

37.0

In [ ]:
np.median(a)

37.0

---

## **12.** 🚀 `np.histogram`

- Numpy has a built-in `numpy.histogram()` function which represents the frequency of data distribution in the graphical form.
 
####  Syntax:`np.histogram(a, bins=10, range=None, density=False)`

#### Parameters
- **`a`** → Input data (array-like).  
- **`bins`** → Number of bins or sequence of bin edges.  
  - Default = `10`.  
- **`range`** → Tuple `(min, max)` → limits for bins.  
- **`density`** → If `True`, normalize so area = 1 (probability density).  



#### What It Does
- Computes a **histogram** of data.  
- Returns:
  1. **Counts** → number of values in each bin.  
  2. **Bin edges** → boundaries of bins.  


In [13]:
# code
a

array([110, 530,  14,  37,  11,  76,  92,   9,  51,  83,  29,  82,  66,
        78,   3], dtype=int32)

In [15]:
np.histogram(a,bins=[0,50,100])

(array([6, 7]), array([  0,  50, 100]))

In [16]:
data = np.array([1, 2, 1, 4, 5, 6, 2, 3, 3, 4])

counts, bins = np.histogram(data, bins=5)
print("Counts:", counts)
print("Bins:", bins)

Counts: [2 2 2 2 2]
Bins: [1. 2. 3. 4. 5. 6.]


---

## **13.** 🚀 `np.corrcoef`

- Return Pearson product-moment correlation coefficients.
- https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

**Syntax:** `np.corrcoef(x, y=None, rowvar=True, bias=False, ddof=None)`

#### Parameters
- **`x, y`** → Input arrays.  
  - If only `x` is given → correlation matrix of `x`.  
  - If both `x` and `y` are given → correlation between `x` and `y`.  
- **`rowvar`** → Default `True`.  
  - If `True`, each row represents a variable.  
  - If `False`, each column represents a variable.  
- **`bias`, `ddof`** → Deprecated; ignore in modern usage.


#### 🔹 What It Does
- Computes the **Pearson correlation coefficient matrix**.  
- Formula:  

![Pearson Correlation](../Pandas/Content/1.png)




- Values range from **-1 to +1**:
  - `+1` → perfect positive correlation  
  - `0` → no correlation  
  - `-1` → perfect negative correlation  



#### ✅ **Takeaway**:  
- `np.corrcoef` gives you the **correlation matrix**.  
- Use it to measure **linear relationships** between variables. 

In [12]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

---

## **14.** 🚀 `np.isin`

- It checks whether each element of one array exists in another array and returns a boolean mask.
- https://numpy.org/doc/stable/reference/generated/numpy.isin.html

**Syntex:** `np.isin(element, test_elements, assume_unique=False, invert=False)`

**Parameters:**
- `element` → Input array (values you want to check).
- `test_elements` → Values to test against.
- `assume_unique` → If `True`, speeds up computation by assuming both arrays contain unique values.
- `invert `→ If `True`, returns `True` for elements **not** in `test_elements`.




In [ ]:
# code
a


array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 30])

---

## **15.** 🚀 `np.flip`

- It `reverses` the order of elements along the specified axis.
- Think of it as `"mirror-flipping"` the array.

**Syntex:** `np.flip(m, axis=None)`


**Parameters:**
- `m` → Input array.
- `axis` → Axis along which to flip.
  - `None` → Flip along all axes (reverse the entire array).
  - `0` → Flip along `rows`.
  - `1` → Flip along `columns` (for 2D arrays).
  - Any valid axis index for higher dimensions.

In [17]:
# code
a

array([110, 530,  14,  37,  11,  76,  92,   9,  51,  83,  29,  82,  66,
        78,   3], dtype=int32)

#### ⭐ **15.1** Flip `1-D` Array:

In [18]:
np.flip(a)

array([  3,  78,  66,  82,  29,  83,  51,   9,  92,  76,  11,  37,  14,
       530, 110], dtype=int32)

In [21]:
b

array([[56, 76, 18, 51],
       [41, 67, 65, 11],
       [50, 76, 76, 33],
       [ 3,  2, 64,  3],
       [95, 35,  8, 80],
       [92, 22, 71, 80]], dtype=int32)

In [ ]:
np.flip(b,axis=1)

array([[51, 18, 76, 56],
       [11, 65, 67, 41],
       [33, 76, 76, 50],
       [ 3, 64,  2,  3],
       [80,  8, 35, 95],
       [80, 71, 22, 92]], dtype=int32)

In [ ]:
np.flip(b,axis=0)

array([[92, 22, 71, 80],
       [95, 35,  8, 80],
       [ 3,  2, 64,  3],
       [50, 76, 76, 33],
       [41, 67, 65, 11],
       [56, 76, 18, 51]], dtype=int32)

---

## **16.** 🚀  `np.put`

- The `numpy.put()` function `**replaces specific elements of an array with given values of p_array**`. Array indexed works on flattened array. 
- https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [9]:
# code
a

array([75, 92, 14, 37, 11, 76, 92,  9, 51, 83, 29, 82, 66, 78,  3],
      dtype=int32)

In [10]:
np.put(a,[0,1],[110,530])

In [11]:
a

array([110, 530,  14,  37,  11,  76,  92,   9,  51,  83,  29,  82,  66,
        78,   3], dtype=int32)

---

## **17.** 🚀 `np.delete`

- The `numpy.delete()` function returns a `new array with the deletion of sub-arrays` along with the mentioned axis. 
- https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [7]:
# code
a

array([75, 92, 14, 37, 11, 76, 92,  9, 51, 83, 29, 82, 66, 78,  3],
      dtype=int32)

In [8]:
np.delete(a,[0,2,4])

array([92, 37, 76, 92,  9, 51, 83, 29, 82, 66, 78,  3], dtype=int32)

---

## **18.** 🚀 🧩 Set functions

- $np.union1d$
- $np.intersect1d$
- $np.setdiff1d$
- $np.setxor1d$
- $np.in1d$

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

<br>

#### 1️⃣ `np.union1d(x, y)`:- Returns the sorted union of two arrays (`all unique elements from both)`.

In [ ]:
np.union1d(m,n)

<br> 

#### 2️⃣ `np.intersect1d(x, y)`:- Returns the sorted intersection (`common elements`).

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

<br>

#### 3️⃣ `np.setdiff1d(x, y):` Returns `elements in x` that `are not in y`.

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

<br>

#### 4️⃣ `np.setxor1d(x, y)`: Returns elements that are in **either** `x` or `y` **but not both** (symmetric difference).

In [5]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

<br>

#### 5️⃣ `np.in1d(x, y)`
- Tests whether **each element of x** is **in y**.
- Returns a boolean array.

In [ ]:
m[np.in1d(m,1)]

array([1])

---

## **19.** 🚀 `np.clip`

- `numpy.clip()` function is `used to Clip (limit) the values in an array`.
- https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [24]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 37, 25, 75, 75, 25, 51, 75, 29, 75, 66, 75, 25],
      dtype=int32)

---

## **20.** 🚀 `np.swapaxes`

 - It interchanges `two axes of an array`.
- Think of it as rotating dimensions — useful for reshaping or re‑orienting data.

**Syntex:** `np.swapaxes(a, axis1, axis2)`

**Parameters:**
- `a `→ Input array.
- `axis1` → First axis to swap.
- `axis2` → Second axis to swap.


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print("a:")
print(a)

print()

print("swapped axis:")
print(np.swapaxes(a, 0, 1))

a:
[[1 2 3]
 [4 5 6]]

swapped axis:
[[1 4]
 [2 5]
 [3 6]]


---

## **21.** 🚀 `np.count_nonzero`

- Counts the number of `non‑zero elements` in an array.
- 👉 Useful for quickly checking sparsity or filtering data.

**Parameter:**
- `a` → Input array.
- `axis` → Axis along which to count.
  - `None` → Counts across the entire array.
  - `0` → Counts non‑zeros `column‑wise`.
  - `1` → Counts non‑zeros `row‑wise`.

In [27]:
a = np.array([[0, 1, 7],
              [2, 0, 0],
              [3, 4, 0]])

print(np.count_nonzero(a))

5


### ⭐ `1` → Counts non‑zeros `row‑wise`.

In [28]:
print(np.count_nonzero(a, axis=1))
# Output: [2 1 2]


[2 1 2]


### ⭐ `0` → Counts non‑zeros `column‑wise`.

In [29]:
print(np.count_nonzero(a, axis=0))

[2 2 1]


---

## **22.** `np.tile`

- It constructs a new array by repeating the input array the specified number of times.
- 👉 Think of it as "tiling" the array like floor tiles.

**syntex:** `np.tile(A, reps)`

**Parameters:**
- `A` → Input array.
- `reps` → Number of repetitions.
  - Can be an integer (repeat along one axis).
  - Or a tuple (repeat along multiple axes).



#### ✅ `1D Array:`

In [32]:


k = np.array([1, 2, 3])

print(k)

print()

print(np.tile(k, 2))



[1 2 3]

[1 2 3 1 2 3]


#### ✅ `2D Array:`

In [33]:
t = np.array([[1, 2], [3, 4]])

print(t)

print()

print(np.tile(t, (2, 3)))


[[1 2]
 [3 4]]

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


---

## **23.** 🚀 `np.repeat`
- **Purpose:** duplicates elements of an array
- https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5
- **Syntex:** np.repeat(a, repeats, axis=None)


#### Parameters
- `a` → Input array.
- `repeats` → Number of times each element is repeated.
  - Can be an integer (same repeat count for all elements).
  - Or an array (different repeat counts per element).
- `axis` → Axis along which to repeat.
  - `None` (default): Flattens the array before repeating.
  - `0 `or `1`: Repeat along rows or columns (for 2D arrays).

#### 🍄 **Example A.** Repeat each item `two` times in array

In [3]:
a = np.array([1, 2, 3])
print(np.repeat(a, 2))


[1 1 2 2 3 3]


#### 🍄 **Example B.** `Different repeat` counts per element

In [5]:
print(np.repeat(a, [1, 2, 3]))


[1 2 2 3 3 3]


#### 🍄 **Example C.**  With `2D` array and `axis`
- Repeat along `axis=0 `(rows)
- Repeat along `axis=1` (columns)

In [4]:
b = np.array([[1, 2], [3, 4]])

# Repeat along axis=0 (rows)
print("Row wise:")
print(np.repeat(b, 2, axis=0))

print()

# Repeat along axis=1 (columns)
print("Column wise:")
print(np.repeat(b, 2, axis=1))



Row wise:
[[1 2]
 [1 2]
 [3 4]
 [3 4]]

Column wise:
[[1 1 2 2]
 [3 3 4 4]]


---


## **24.** 🚀 `np.allclose`

- **Purpose:** Compares `two arrays element-wise to check `if they are `approximately equal` within a tolerance.
- **Syntex:** `np.allclose(a, b, rtol=1e-05, atol=1e-08)`


| Parameter | Meaning | Default | Example Impact |
| --- | --- | --- | --- |
| `a`, `b` | Arrays to compare | Required | ``[1,2,3] ``vs ``[1,2.000001,3]`` |
| ``rtol`` | Relative tolerance | ``1e-05`` | Allows small % differences |
| ``atol`` | Absolute tolerance | ``1e-08`` | Allows fixed small differences |
| Return | Boolean | — | True/False |

### np.allclose `Numpy` vs `Pandas`

| Feature | ``np.allclose`` (NumPy) | ``equals`` (Pandas) |
| --- | --- | --- |
| **Tolerance** | Yes (``rtol``, ``atol``) | No (strict match) |
| **Data Types** | NumPy arrays | Pandas objects |
| **Use Case** | Floating-point comparisons | Exact equality check |
| **Return** | Boolean (True/False) | Boolean (True/False) |

#### 🍄 **Example A.** `True` Scenario

In [1]:

# 25. np.allclose and equals
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.0000001, 3.0])

print(np.allclose(a, b))  # True (difference within tolerance)


True


#### 🍄 **Example B.** `False` Scenario

In [2]:

a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 5.0, 3.0])

print(np.allclose(a, b))  # False (difference is too big)


False


---